In [1]:
%matplotlib inline

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy
import random

# Reading 'xlsx' files requires openpyxl
# Install openpyxl 3.1 rather than 3.1.1

data_path = 'data//'

# AidData ChinesePublicDiplomacy.csv: provides country-year aggregates for each public diplomacy measure
# https://www.aiddata.org/data/chinas-public-diplomacy-dashboard-dataset-version-2);
fname_aidd = 'data1_AidData.csv'
fname_cari = 'data2_CARI.xlsx'
fname_bank = 'data3_WorldBank.txt'
# SAIS CARI debt relief: http://www.sais-cari.org/debt-relief
# World Bank: https://databank.worldbank.org/source/world-development-indicators

data_aidd = pd.read_csv(data_path + fname_aidd, sep=',')
data_canc = pd.read_excel(data_path + fname_cari, sheet_name='Cancellation', engine='openpyxl')
data_rest = pd.read_excel(data_path + fname_cari, sheet_name='Restructuring', engine='openpyxl')
data_bank = pd.read_csv(data_path + fname_bank, sep='\t')

In [9]:
##################
# Clean datasets #
##################

# AidData
# Rename column 'year' to 'Year' & 'receiving country' to 'Country'
data_aidd = data_aidd.rename(columns={'year': 'Year', 'receiving_country': 'Country'})

# CARI cancellation
# Drop empty columns in CARI cancellation, as well as 'ID' and 'Sources' columns
data_canc = data_canc[['Country', 'Year', 'USD Millions']]
# Drop empty rows in CARI cancellation
data_canc = data_canc[data_canc.Country.isna()==False]
# Convert 'Year' column from float to integer
data_canc['Year'] = data_canc['Year'].astype(int)
# Sum up the amount of several cancellations per country per year (Zambia, 2019)
data_canc = data_canc.groupby(['Country', 'Year']).sum().reset_index()
# This converts missing numbers to zeros, reverse that
data_canc['USD Millions'] = data_canc['USD Millions'].replace(0, np.nan)

data_canc

     Country  Year  USD Millions
0     Angola  2007          7.00
1     Angola  2009          3.00
2     Angola  2017          7.27
3      Benin  2002         10.00
4      Benin  2007           NaN
..       ...   ...           ...
88    Zambia  2006        211.00
89    Zambia  2007         11.77
90    Zambia  2011         37.50
91    Zambia  2019         92.00
92  Zimbabwe  2015         40.00

[93 rows x 3 columns]

In [10]:
# CARI restructuring
# Rename column '# of loans'
data_rest = data_rest.rename(columns={'# of loans (0 for duplicates, figures represent "at least")': 'Number of loans'})
# Retain only columns 'Country', 'Year', 'USD Millions', '# of loans'
data_rest = data_rest[['Country', 'Year', 'USD Millions', 'Number of loans']]
# Drop empty rows
data_rest = data_rest[data_rest.Country.isna()==False]
# Drop last row with no indication of year
data_rest = data_rest[:-1]
# Convert 'Year' column from float to integer
data_rest['Year'] = data_rest['Year'].astype(int)
# Remove asterisks from values
data_rest['USD Millions'] = data_rest['USD Millions'].astype(str).str.replace('*', '')
data_rest['USD Millions'] = data_rest['USD Millions'].astype(float)

data_rest

C:\Users\Conrad\anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  del sys.path[0]

       Country  Year  USD Millions  Number of loans
0     Cameroon  2002          5.15                1
1     Zimbabwe  2003         42.00                1
2        Benin  2004         17.00                1
3     Zimbabwe  2004         18.00                2
4     Zimbabwe  2007         55.00                0
5     Zimbabwe  2010         55.00                0
6   Seychelles  2011         24.00                3
7     Zimbabwe  2012        200.00                1
8        Sudan  2012           NaN                1
9       Angola  2016       7500.00                4
10        Chad  2017        447.00                3
11  Mozambique  2017       2020.00                1
12       Niger  2018        161.00                1
13    Ethiopia  2018       2490.00                1
14         ROC  2018        116.00                1
15    Cameroon  2019        253.00                1
16         ROC  2019       1612.00                8

In [11]:
# World Bank
# Rename column 'Country Name' to 'Country'
data_bank = data_bank.rename(columns={'Country Name': 'Country'})
# Drop columns 'Country Code' and 'Series Code'
data_bank = data_bank.drop(['Country Code', 'Series Code'], axis=1)
# Drop last five rows which are descriptive
data_bank = data_bank[:-5]
# Rename year columns from 'YYYY [YRYYYY]' to 'YYYY' (i.e., retain first 4 digits)
cols_bank = data_bank.columns.to_list()
years = [int(col[0:4]) for col in cols_bank[2:]]
cols_bank_re = cols_bank[:2] + years
# Build a dictionary that maps old to new column names, as pd library requires a dictionary to rename columns
d_cols = {}
for col_old, col_new in zip(cols_bank, cols_bank_re):
    d_cols[col_old] = col_new
data_bank = data_bank.rename(columns=d_cols)
# Convert columns with numerical values to type float
for col in years:
    data_bank[col] = data_bank[col].replace('..', np.nan).astype('float')

data_bank

,Country,Series Name,1960,1961,1962,1963,1964,1965,1966,1967,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Exports of goods and services (% of GDP),4.132233e+00,4.453443e+00,4.878051e+00,9.171601e+00,8.888893e+00,1.125828e+01,8.571429e+00,6.772908e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,"Foreign direct investment, net inflows (% of GDP)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.930249e-01,2.854411e-01,2.398013e-01,2.096648e-01,8.840009e-01,5.166064e-01,2.747966e-01,6.615720e-01,1.244959e-01,NaN
2,Afghanistan,GDP (current US$),5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,1.780511e+10,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10
3,Afghanistan,GDP growth (annual %),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.263548e-01,1.275229e+01,5.600745e+00,2.724543e+00,1.451315e+00,2.260314e+00,2.647003e+00,1.189228e+00,3.911603e+00,-2.351101e+00
4,Afghanistan,GDP per capita (current US$),5.977323e+01,5.986090e+01,5.845801e+01,7.870643e+01,8.209531e+01,1.011083e+02,1.375943e+02,1.608984e+02,...,5.911900e+02,6.388459e+02,6.243155e+02,6.142233e+02,5.560072e+02,5.120128e+02,5.166799e+02,4.856684e+02,4.941793e+02,5.167479e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8773,World,Human capital index (HCI) (scale 0-1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8774,World,Employment in agriculture (% of total employme...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.204912e+01,3.114816e+01,3.034102e+01,2.943039e+01,2.883455e+01,2.831972e+01,2.780048e+01,2.721844e+01,2.675445e+01,NaN
8775,World,Employment in industry (% of total employment)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.286771e+01,2.331004e+01,2.327623e+01,2.330366e+01,2.313655e+01,2.301733e+01,2.286602e+01,2.293710e+01,2.267242e+01,NaN
8776,World,Employment in services (% of total employment)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.508414e+01,4.554224e+01,4.638349e+01,4.726712e+01,4.802886e+01,4.866297e+01,4.933498e+01,4.984510e+01,5.057464e+01,NaN
8777,World,International migrant stock (% of population),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.342797e+00,NaN,NaN,NaN,NaN,NaN

In [ ]:
##################
# Merge datasets #
##################

# Merge datasets according to the formatting of the World Bank data
data = deepcopy(data_bank)

# Harmonize country names across datasets
# Get country naming of each data source
countries_aidd = list(data_aidd.Country.unique())
countries_canc = list(data_canc.Country.unique())
countries_rest = list(data_rest.Country.unique())
countries_bank = list(data_bank.Country.unique())

# Take world bank country names as basis
# See whether any country name is not contained in the bank's list
countries = list(set(countries_rest).difference(countries_bank))
# ROC (Taiwan) is not part of the bank's list
countries_re_rest = {'ROC': 'Republic of China'}
# Rename
data_rest['Country'] = data_rest['Country'].replace(countries_re_rest)

countries = list(set(countries_canc).difference(countries_bank))
countries_re_canc = {'ROC': 'Republic of China',
                     'DRC': 'Congo, Dem. Rep.',
                     'CAR': 'Central African Republic',
                     'The Gambia': 'Gambia, The',
                     'Cape Verde': 'Cabo Verde',
                     'Sao Tome & Principe': 'Sao Tome and Principe',
                     "Cote D'Ivoire": "Cote d'Ivoire"}
data_canc['Country'] = data_canc['Country'].replace(countries_re_canc)

countries = list(set(countries_aidd).difference(countries_bank))
countries_re_aidd = {'North Korea': "Korea, Dem. People's Rep.",
                     'Laos': 'Lao PDR',
                     'Micronesia': 'Micronesia, Fed. Sts.',
                     'Brunei': 'Brunei Darussalam',
                     'Kyrgyzstan': 'Kyrgyz Republic',
                     'South Korea': 'Korea, Rep.'}
data_aidd['Country'] = data_aidd['Country'].replace(countries_re_aidd)

cols = data.columns.to_list()
# Merge each indicator of the AidData dataset with the main dataset
aidd_indicators = data_aidd.columns.to_list()[2:]
for col_name in aidd_indicators:
    # Reshape the data according to the world bank format: columns become rows and years become columns
    indicator = data_aidd.pivot(index='Country', columns='Year', values=col_name).reset_index()
    indicator.insert(1, 'Series Name', col_name)
    cols_indicator = indicator.columns.to_list()
    # Extract common columns, based on which the two datasets will be merged
    cols_common = [c for c in cols_indicator if c in cols]
    # Merge the main dataset with the indicator
    data = pd.merge(data, indicator, on=cols_common, how='outer')

# Merge the CARI cancellation dataset with the main dataset
# Reshape the data according to the world bank format: columns become rows and years become columns
indicator = data_canc.pivot(index='Country', columns='Year', values='USD Millions').reset_index()
indicator.insert(1, 'Series Name', 'Debt Cancellation [US$ Millions]')
cols_indicator = indicator.columns.to_list()
# Extract common columns, based on which the two datasets will be merged
cols_common = [c for c in cols_indicator if c in cols]
# Merge the main dataset with the indicator
data = pd.merge(data, indicator, on=cols_common, how='outer')

# Merge the CARI restructuring dataset with the main dataset
# First, the total amount of debt restructuring per country per year
# Reshape the data according to the world bank format: columns become rows and years become columns
indicator = data_rest.pivot(index='Country', columns='Year', values='USD Millions').reset_index()
indicator.insert(1, 'Series Name', 'Debt Restructuring [US$ Millions]')
cols_indicator = indicator.columns.to_list()
# Extract common columns, based on which the two datasets will be merged
cols_common = [c for c in cols_indicator if c in cols]
# Merge the main dataset with the indicator
data = pd.merge(data, indicator, on=cols_common, how='outer')

# Second, the number of loans restructured per country per year
# Reshape the data according to the world bank format: columns become rows and years become columns
indicator = data_rest.pivot(index='Country', columns='Year', values='Number of loans').reset_index()
indicator.insert(1, 'Series Name', 'Number of loans restructured')
cols_indicator = indicator.columns.to_list()
# Extract common columns, based on which the two datasets will be merged
cols_common = [c for c in cols_indicator if c in cols]
# Merge the main dataset with the indicator
data = pd.merge(data, indicator, on=cols_common, how='outer')

# Save dataset
data.to_csv(path_or_buf=data_path+'task2_dataset.csv', sep=',', index=False)

# Read dataset
data = pd.read_csv(data_path+'task2_dataset.csv', sep=',')

CPIA debt policy rating #
##########################

In [ ]:
# CPIA criteria
# https://thedocs.worldbank.org/en/doc/69484a2e6ae5ecc94321f63179bfb837-0290032022/original/CPIA-Criteria-2021.pdf, pp. 12-14
# Rating 1 a. "the country has recently engaged or in the near future will likely engage in debt restructuring negotiations"
# In other words, likely future, current, or recent debt restructuring should drag the rating down
# On the other hand, it is unclear whether this part of the 2021 rating has been applied throughout 2000-2020

# Methodology:
# a) contrast the amount of debt cancellation received with the mean CPIA debt policy rating for each country
# b) evaluate the correlation of debt cancellation time series with the CPIA rating time series (Pearson coefficient)

# Get a list of countries who received debt cancellation from China AND for which exists a CPIA rating
countries_canc = list(data.loc[data['Series Name'] == 'Debt Cancellation [US$ Millions]'].Country.unique())
countries_cpia = list(data.loc[data['Series Name'] == 'CPIA debt policy rating (1=low to 6=high)'].Country.unique())
countries = list(set(countries_canc) & set(countries_cpia))

# For each country, calculate Pearson correlation coefficient between CPIA and amt of debt cancellation
# Also, for each country get the average debt rating and the total amount of debt cancellation
r_cpia_canc = {}
cpia_avg = {}
canc_tot = {}
for country in countries:
    # Get a time series of cpia ratings for the country under scrutiny
    cpia = data.loc[data['Country'] == country].loc[data['Series Name'] == 'CPIA debt policy rating (1=low to 6=high)']
    cpia = cpia.iloc[0, 2:]
    cpia_mean = cpia.mean()
    # If all ratings for that country are missing, skip it
    if cpia.isnull().all():
        pass
    # If cpia ratings are populated, continue
    else:
        # CPIA ratings started being assigned only in the 2000s, so to calculate the correlation over the entire time series:
        # Fill earlier, non-populated CPIA ratings with the first ever assigned rating
        # This shouldn't matter as the correlation method considers differences rather than absolute values
        cpia = cpia.fillna(cpia[cpia.first_valid_index()]).astype(float)
        # Get a time series of debt cancellations for the country under scrutiny
        canc = data.loc[data['Country'] == country].loc[data['Series Name'] == 'Debt Cancellation [US$ Millions]']
        # Fill empty fields of debt cancellation amount with 0
        canc = canc.iloc[0, 2:].fillna(0).astype(float)
        # Cumulate received amount of debt cancellation, as this is necessary for a meaningful calculation of the correlation
        canc = canc.cumsum()
        # Calculate the Pearson coefficient
        r = cpia.corr(canc, method='pearson')
        # If the coefficient is not-a-number, this means that the debt policy rating has been constant
        # In this case, the coefficient can be set to 0, as there appears to be no correlation
        if np.isnan(r):
            r_cpia_canc[country] = 0
            cpia_avg[country] = cpia_mean
            canc_tot[country] = canc.iloc[-1]
        else:
            r_cpia_canc[country] = r
            cpia_avg[country] = cpia_mean
            canc_tot[country] = canc.iloc[-1]

# Visualize total debt cancellation vs cpia rating
fig, ax = plt.subplots()
for country in canc_tot.keys():
    color = "#" + "%06x" % random.randint(0, 0xFFFFFF)
    ax.scatter(canc_tot[country], cpia_avg[country], label=country, c=color)
ax.legend(fontsize=5)
ax.set_xlabel('Total amount of debt cancellation received by a country [million USD]', fontsize=12)
ax.set_ylabel('CPIA debt policy rating (higher rating, better policy)', fontsize=12)

# Based on this visualization, there doesn't seem to be a trend that would, across countries, generally push the CPIA rating
# into a certain direction, based on the amount of debt cancellation received. However, it is possible that such a trend would
# appear if we could control for other variables that might influence the CPIA rating, and isolate the influence of the amount of
# debt cancellation

# Visualize correlation coefficient by country
# Between 1 and 0: positive correlation (series a increases, series b increases)
# 0: no correlation
# Between 0 and -1: negative correlation (series a increases, series b decreases)
# Calculate mean and std of the correlation coefficient and plot the results
r_countries = list(r_cpia_canc.keys())
r_values = list(r_cpia_canc.values())
r_mean = np.nanmean(r_values)
r_std = np.nanstd(r_values)

fig, ax = plt.subplots()
x_axis = np.arange(0, len(r_cpia_canc), 1)
ax.set_axisbelow(True)
ax.grid(color='gray', linestyle='dashed', alpha=0.5)
ax.scatter(x_axis, r_values)
ax.scatter(np.mean(x_axis), r_mean, c='red', label='mean', marker='*', s=100)
ax.scatter(np.mean(x_axis), r_std, c='green', label='std', marker='*', s=100)
ax.legend()
ax.set_xticks(x_axis)
ax.set_xticklabels(r_countries, rotation=90)
ax.set_xlabel('Country', fontsize=12)
ax.set_ylabel('Pearson correlation coefficient', fontsize=12)

# The average correlation for a country is mildly positive (i.e. amt of debt cancellation increases, debt policy rating increases)
# This is not what was expected in light of the criteria for setting the CPIA rating explained above. However, the interpretation
# of the mean becomes less expressive in light of the significant standard deviation
# An interesting observation is also that the results appear to cluster in three regions:
# Little correlation, strong negative correlation (smaller than -0.5), strong positive correlation (larger than 0.5).
# This could be coincidence, or that Chinese debt cancellation simply doesn't matter much in the CPIA process,
# but it could also hint at a third factor that is at play, possibly related to political orientation, which may decide whether
# debt cancellation by China influences the CPIA rating to the positive or to the negative.

# Limitation of the method and how to improve on it
# The temporal resolution of this method is not very granular. It seems intuitive that a case of debt cancellation has the most
# influence on the CPIA rating in the years surrounding the event. However, the Pearson correlation coefficient considers a very
# long time horizon. For example, if a country receives debt cancellation in 2003, and the CPIA rating increases in 2017, the
# Pearson coefficient would still capture this and be tilted towards a positive value, even though it seems unlikely in practice
# that a debt cancellation from 2003 influences the CPIA rating in 2017. This could be mitigated by extracting time intervals
# surrounding the events of debt cancellation by a few years, and then calculating the correlation on that.
# In addition, as mentioned previously, an isolation of the effect of debt cancellation on the CPIA rating by controlling for
# other variables that may affect the debt rating would also be desirable.

Number of government visits #
##############################

In [ ]:
# Get a list of countries who received debt cancellation from China AND for which exists data on government visits
countries_canc = list(data.loc[data['Series Name'] == 'Debt Cancellation [US$ Millions]'].Country.unique())
countries_govt = list(data.loc[data['Series Name'] == 'government_visits'].Country.unique())
countries = list(set(countries_canc) & set(countries_govt))

# As the two data streams are mutually exclusive in their country coverage, there is no analysis to do

#############
# NB Viewer #
#############

# Jupyter notebook can be started via command line
# Figure out how to update the environment used in the jupyter notebook
# Try uploading the executed Jupyter notebook onto my Github

# Set up NBviewer